### ISSUE TITLE
폴더구조에 대해 질문드립니다. 

### ISSUE THREAD

**Issue by KhelKim** [JJayeee/TIL#2]
왜 00 startcamp 다음에 01로 시작하지 않죠?

**Comment by KhelKim** [comment]
이슈해결된거 확인했습니다.

**Comment by JJayeee** [comment]
zzzzzzzzzzzzzzzzzzㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ자체 확인해주시다니 너무 감사드리고
저도 다른 폴더도 확인해서 수정해 두었습니다. 구독팔로관심 늘 감사드려요~
